# GAME : "Hypercube-v0"
# GAME : "Pendulum-v0"
# GAME : "LunarLanderContinuous-v2"
# GAME : "BipedalWalker-v2"
# GAME : "HandManipulateBlock-v0"
# GAME : "HandManipulateBlockCustom-v0"
#GAME : {id: HandManipulateBlockCustom-v0}

# GAME: {id: 'HandManipulateBlockCustom-v0',
#   entry_point: 'gym.envs.robotics:HandBlockEnv',
#   kwargs: {'target_position': 'random', 'target_rotation': 'xyz','reward_type': 'dense'},
#   max_episode_steps: 500,
#   }

# GAME: {id: 'FetchSlideCustom-v1',
#   entry_point: 'gym.envs.robotics:FetchSlideEnv',
#   kwargs: {'reward_type': 'dense'},
#   max_episode_steps: 500,
# }

GAME: {id: 'FetchReach-v1'}
HIDDEN_VALUE_LAYERS : [256,256]
HIDDEN_Q_LAYERS : [256,256]
HIDDEN_PI_LAYERS : [256,256]

MEMORY_CAPACITY : 1000000
BATCH_SIZE : 256
GAMMA : 0.99
VALUE_LR : 0.0003
SOFTQ_LR : 0.0003
ACTOR_LR : 0.0003

TAU : 0.005

AUTO_ALPHA : True
ALPHA_LR : 0.0003

MAX_EPISODES : 50000
#MAX_STEPS : 500  # Max steps per episode

FREQ_PLOT : 10
FREQ_EVAL : 25
FREQ_SAVE : 250
