# GAME : "Hypercube-v0"
# GAME : "Pendulum-v0"
# GAME : "LunarLanderContinuous-v2"
# GAME : "BipedalWalker-v2"
# GAME : "HandManipulateBlock-v0"
GAME : {id: HandManipulateBlock-v0}

HIDDEN_VALUE_LAYERS : [256,256]
HIDDEN_Q_LAYERS : [256,256]
HIDDEN_PI_LAYERS : [256,256]

MEMORY_CAPACITY : 1000000
BATCH_SIZE : 256
GAMMA : 0.99
VALUE_LR : 0.0003
SOFTQ_LR : 0.0003
ACTOR_LR : 0.0003

TAU : 0.005

AUTO_ALPHA : True
ALPHA_LR : 0.0003

MAX_EPISODES : 10000
MAX_STEPS : 500  # Max steps per episode

FREQ_PLOT : 10
FREQ_EVAL : 25
FREQ_SAVE : 250
