# GAME : "Hypercube-v0"
# GAME : "Pendulum-v0"
# GAME : "LunarLanderContinuous-v2"
# GAME : "BipedalWalker-v2"
# GAME : "HandManipulateBlock-v0"
GAME : {id: HandManipulateBlock-v0}

HIDDEN_VALUE_LAYERS : [128, 128, 128]
HIDDEN_Q_LAYERS : [128, 128, 128]
HIDDEN_PI_LAYERS : [128, 128, 128]

MEMORY_CAPACITY : 1000000
BATCH_SIZE : 100
GAMMA : 0.99
VALUE_LR : 0.001
SOFTQ_LR : 0.001
ACTOR_LR : 0.001

TAU : 0.005

AUTO_ALPHA : True
ALPHA_LR : 0.001

MAX_EPISODES : 10000
MAX_STEPS : 50  # Max steps per episode

FREQ_PLOT : 10
FREQ_EVAL : 25
FREQ_SAVE : 250
